apiVersion: v1
kind: ConfigMap
metadata:
  name: listener-app-config
  namespace: listener-app-dev
data:
  # Backend configuration
  ENVIRONMENT: "development"
  BACKEND_CORS_ORIGINS: '["http://localhost:3000", "https://dev.listener-app.example.com"]'
  PROJECT_NAME: "Listener App API"
  API_V1_STR: "/api/v1"
  SERVER_HOST: "https://dev-api.listener-app.example.com"
  
  # Scraper configuration
  SCRAPING_INTERVAL_MINUTES: "60"
  MAX_SONGS_PER_BLOG: "50"
  
  # Frontend configuration
  REACT_APP_API_URL: "https://dev-api.listener-app.example.com"
  REACT_APP_ENV: "development" 