apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: listener-app-dev
  labels:
    app: scraper
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
        environment: development
    spec:
      containers:
      - name: scraper
        image: ${REGISTRY}/${SCRAPER_IMAGE_NAME}:develop
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "300m"
            memory: "384Mi"
          requests:
            cpu: "150m"
            memory: "192Mi"
        envFrom:
        - configMapRef:
            name: listener-app-config
        - secretRef:
            name: listener-app-secrets
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-scraper
  namespace: listener-app-dev
spec:
  schedule: "0 */1 * * *"  # Run every hour
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: scraper-job
            environment: development
        spec:
          containers:
          - name: scraper
            image: ${REGISTRY}/${SCRAPER_IMAGE_NAME}:develop
            imagePullPolicy: Always
            args:
            - "run-scrapers"
            - "--all"
            resources:
              limits:
                cpu: "500m"
                memory: "512Mi"
              requests:
                cpu: "200m"
                memory: "256Mi"
            envFrom:
            - configMapRef:
                name: listener-app-config
            - secretRef:
                name: listener-app-secrets
          restartPolicy: OnFailure 