apiVersion: v1
kind: Secret
metadata:
  name: listener-app-secrets
  namespace: listener-app-dev
type: Opaque
stringData:
  # Database configuration
  POSTGRES_SERVER: "postgres-svc.listener-app-dev.svc.cluster.local"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres-dev-password"
  POSTGRES_DB: "listener_app_dev"
  
  # Redis configuration
  REDIS_HOST: "redis-svc.listener-app-dev.svc.cluster.local"
  REDIS_PASSWORD: "redis-dev-password"
  
  # JWT and security
  SECRET_KEY: "dev-secret-key-replace-in-production"
  JWT_SECRET: "dev-jwt-secret-replace-in-production"
  
  # For S3 storage (if used)
  AWS_ACCESS_KEY_ID: "dev-access-key"
  AWS_SECRET_ACCESS_KEY: "dev-secret-key"
  AWS_STORAGE_BUCKET_NAME: "listener-app-dev" 