apiVersion: v1
kind: Secret
metadata:
  name: listener-app-secrets
  namespace: listener-app-prod
type: Opaque
stringData:
  # Database configuration
  POSTGRES_SERVER: "postgres-svc.listener-app-prod.svc.cluster.local"
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "listener_app_prod"
  
  # Redis configuration
  REDIS_HOST: "redis-svc.listener-app-prod.svc.cluster.local"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  
  # JWT and security
  SECRET_KEY: "${SECRET_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
  
  # For S3 storage (if used)
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  AWS_STORAGE_BUCKET_NAME: "listener-app-prod" 